{{- if eq .Values.routing.mode "router" }}
{{- $ns := include "oaf.namespace" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oaf.fullname" . }}-router
  namespace: {{ $ns }}
  labels:
    {{- include "oaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: router
spec:
  replicas: {{ .Values.router.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "oaf.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: router
  template:
    metadata:
      labels:
        {{- include "oaf.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: router
      {{- with .Values.router.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.router.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.router.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.router.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx
          image: {{ include "oaf.image" .Values.images.router }}
          imagePullPolicy: {{ .Values.images.router.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.router.resources | nindent 12 }}
      volumes:
        - name: conf
          configMap:
            name: {{ include "oaf.fullname" . }}-router-conf
{{- end }}
