#!/usr/bin/env python3
"""
Skill 实现代码生成器

根据 OAF Skills 配置生成 Python 实现代码。
"""

from pathlib import Path
from typing import Optional
import json


class SkillCodeGenerator:
    """Skill 实现代码生成器"""

    def __init__(self, skill_dir: Path | str):
        self.skill_dir = Path(skill_dir)
        self.scripts_dir = self.skill_dir / "scripts"

    def generate(self, skill_config: dict) -> dict[str, str]:
        """根据 Skill 配置生成实现代码"""
        files = {}

        skill_name = skill_config.get("name", "unnamed-skill")
        skill_description = skill_config.get("description", "")

        implementation = skill_config.get("implementation", {})
        impl_type = implementation.get("type", "python")

        if impl_type == "python":
            code = implementation.get("code", "")
            if code:
                files[f"{skill_name.replace('-', '_')}.py"] = code
            else:
                files[f"{skill_name.replace('-', '_')}.py"] = self._render_default_skill_py(
                    skill_name, skill_description
                )

        return files

    def generate_all(self, agent_dir: Path | str, skills_config: list[dict]) -> dict[str, dict]:
        """为所有技能生成实现代码"""
        agent_dir = Path(agent_dir)
        results = {}

        for skill in skills_config:
            name = skill.get("name", "unknown")
            skill_dir = agent_dir / "skills" / name

            if skill.get("source") == "local":
                self.skill_dir = skill_dir
                skill_dir.mkdir(parents=True, exist_ok=True)

                self._ensure_skill_md(skill_dir, name, skill.get("description", ""))

                files = self.generate(skill)

                scripts_dir = skill_dir / "scripts"
                scripts_dir.mkdir(exist_ok=True)

                for filename, content in files.items():
                    (scripts_dir / filename).write_text(content, encoding="utf-8")

                results[name] = {"status": "generated", "files": list(files.keys())}

        return results

    def _render_default_skill_py(self, name: str, description: str) -> str:
        """生成默认的 Skill Python 实现"""
        safe_name = name.replace("-", "_")
        return f'''#!/usr/bin/env python3
"""
Skill: {name}
Description: {description}
Generated by Codegen
"""

import json
import os
from typing import Any, Optional


class {safe_name.title().replace("_", "")}:
    """Skill implementation for {name}"""

    def __init__(self):
        self.name = "{name}"
        self.description = "{description}"

    def run(self, input_data: Any = None, **kwargs) -> str:
        """Execute the skill with given input"""
        return self.process(input_data, **kwargs)

    def process(self, input_data: Any = None, **kwargs) -> str:
        """Override this method with custom skill logic"""
        return f"[Skill: {name}] Processed: {{input_data}}"


def main():
    """CLI entry point for standalone execution"""
    import sys

    skill = {safe_name.title().replace("_", "")}()

    if len(sys.argv) > 1:
        input_data = " ".join(sys.argv[1:])
    else:
        input_data = sys.stdin.read().strip()

    result = skill.run(input_data)
    print(result)


if __name__ == "__main__":
    main()
'''

    def _ensure_skill_md(self, skill_dir: Path, name: str, description: str):
        """确保 SKILL.md 存在"""
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            skill_md_content = f'''---
name: "{name}"
description: "{description}"
license: "MIT"
metadata:
  author: "local"
  version: "1.0.0"
allowed-tools: ["bash", "python"]
---

# {name}

{description}

## Usage

使用说明...
'''
            skill_md.write_text(skill_md_content, encoding="utf-8")

        init_file = skill_dir / "scripts" / "__init__.py"
        init_file.parent.mkdir(parents=True, exist_ok=True)
        if not init_file.exists():
            init_file.write_text("", encoding="utf-8")
