#!/usr/bin/env python3
"""
DeepAgents 代码生成器

输入: Agent 配置 JSON
输出: 完整的 DeepAgents Python 脚本 + Dockerfile + requirements.txt
"""

import json
import os
import sys
from pathlib import Path

TEMPLATE_DIR = Path(__file__).parent / "templates"


def generate_agent_code(config: dict) -> dict:
    """
    根据配置生成 DeepAgents 代码文件
    
    Args:
        config: Agent 配置字典
        
    Returns:
        dict: {"agent.py": str, "Dockerfile": str, "requirements.txt": str}
    """
    name = config["name"]
    description = config.get("description", "")
    model = config.get("model", "qwen3.6-plus")
    endpoint = config.get("model_endpoint", "https://dashscope.aliyuncs.com/compatible-mode/v1")
    api_key = config.get("api_key", "")
    system_prompt = config.get("system_prompt", "You are a helpful AI assistant.")
    tools = config.get("tools", [])
    sub_agents = config.get("sub_agents", [])
    enable_memory = config.get("memory", True)
    max_iterations = config.get("max_iterations", 50)

    # 生成 Agent 代码
    agent_py = _render_agent_py(
        name=name,
        description=description,
        model=model,
        endpoint=endpoint,
        api_key=api_key,
        system_prompt=system_prompt,
        tools=tools,
        sub_agents=sub_agents,
        enable_memory=enable_memory,
        max_iterations=max_iterations,
    )

    # 生成 Dockerfile
    dockerfile = _render_dockerfile(name=name)

    # 生成 requirements.txt
    requirements = _render_requirements()

    return {
        "agent.py": agent_py,
        "Dockerfile": dockerfile,
        "requirements.txt": requirements,
    }


def _render_agent_py(
    name: str,
    description: str,
    model: str,
    endpoint: str,
    api_key: str,
    system_prompt: str,
    tools: list,
    sub_agents: list,
    enable_memory: bool,
    max_iterations: int,
) -> str:
    tools_str = json.dumps(tools, ensure_ascii=False)
    sub_agents_str = json.dumps(sub_agents, ensure_ascii=False)

    return f'''#!/usr/bin/env python3
"""
Agent: {name}
Description: {description}
Generated by Agent Manager
"""

import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn
from langchain.chat_models import init_chat_model
from deepagents import create_deep_agent

# ============================================================
# Configuration
# ============================================================
MODEL_NAME = "{model}"
MODEL_ENDPOINT = "{endpoint}"
API_KEY = os.environ.get("LLM_API_KEY", "{api_key}")
SYSTEM_PROMPT = """{system_prompt}"""
TOOLS = {tools_str}
SUB_AGENTS = {sub_agents_str}
ENABLE_MEMORY = {enable_memory}
MAX_ITERATIONS = {max_iterations}

# ============================================================
# Initialize Model and Agent
# ============================================================
model = init_chat_model(
    model=MODEL_NAME,
    model_provider="openai",
    openai_api_key=API_KEY,
    openai_api_base=MODEL_ENDPOINT,
)

agent = create_deep_agent(
    model=model,
    system_prompt=SYSTEM_PROMPT,
)

# ============================================================
# FastAPI Application
# ============================================================
app = FastAPI(
    title="{name}",
    description="{description}",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    message: str
    history: list = []
    stream: bool = False


class ChatResponse(BaseModel):
    success: bool
    data: dict | str
    error: str | None = None


@app.get("/health")
async def health_check():
    return {{"status": "healthy", "agent": "{name}"}}


@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    try:
        messages = []
        for h in request.history:
            messages.append({{"role": h["role"], "content": h["content"]}})
        messages.append({{"role": "user", "content": request.message}})

        result = agent.invoke({{"messages": messages}})

        last_msg = ""
        if "messages" in result:
            for m in reversed(result["messages"]):
                if hasattr(m, "content"):
                    last_msg = m.content
                    break

        return ChatResponse(
            success=True,
            data={{"response": last_msg}},
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/")
async def root():
    return {{
        "agent": "{name}",
        "description": "{description}",
        "model": MODEL_NAME,
        "endpoint": "/chat",
        "health": "/health",
    }}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''


def _render_dockerfile(name: str) -> str:
    return f'''FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY agent.py .

EXPOSE 8000

ENV PYTHONUNBUFFERED=1

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:8000/health || exit 1

CMD ["python", "-u", "agent.py"]
'''


def _render_requirements() -> str:
    return '''deepagents>=0.5.0
langchain>=1.0.0
langchain-openai>=1.0.0
fastapi>=0.100.0
uvicorn>=0.30.0
pydantic>=2.0.0
'''


def validate_config(config: dict) -> list[str]:
    """Validate config against schema, return list of errors"""
    errors = []
    required = ["name", "description", "model", "system_prompt"]
    for field in required:
        if field not in config:
            errors.append(f"Missing required field: {field}")
    if not config.get("name", "").strip():
        errors.append("name cannot be empty")
    return errors


def main():
    """CLI entry point"""
    if len(sys.argv) < 2:
        print("Usage: python generator.py <config.json> [output_dir]")
        print("   or: echo '{{...}}' | python generator.py --stdin [output_dir]")
        sys.exit(1)

    if sys.argv[1] == "--stdin":
        config = json.load(sys.stdin)
        output_dir = sys.argv[2] if len(sys.argv) > 2 else "."
    else:
        with open(sys.argv[1]) as f:
            config = json.load(f)
        output_dir = sys.argv[2] if len(sys.argv) > 2 else Path(sys.argv[1]).parent

    errors = validate_config(config)
    if errors:
        print("Validation errors:")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)

    result = generate_agent_code(config)

    os.makedirs(output_dir, exist_ok=True)
    for filename, content in result.items():
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w") as f:
            f.write(content)
        print(f"Generated: {filepath}")


if __name__ == "__main__":
    main()
